<?php
$productCollection = $block->getProductCollection();
if (count($productCollection) > 0) {
    ?>
    <script type="text/javascript">
        require(['jquery', 'magebuzz/owlcarousel'], function ($) {
            $(document).ready(function () {
                $("#mb-timecountdown-carousel").owlCarousel({
                    autoPlay: 5000, //Set AutoPlay to 3 seconds
                    items: 5,
                    itemsDesktop: [1199, 3],
                    itemsDesktopSmall: [979, 3]
                });
            });
        });
    </script>
    <div class="magebuzz-timecountdown-slider">
        <div id="mb-timecountdown-carousel">
            <?php
            $_helper = $this->helper('Magento\Catalog\Helper\Output');
            foreach ($productCollection as $item) {
                $product = $item->load($item->getId());
                if ($this->getLayout()->createBlock('Magebuzz\Timecountdown\Block\Timecountdown')->isPriceCountdown($product)) {
                    $image = 'category_page_grid';
                    ?>
                    <ol class="products lists items product-items">
                        <li class="item product product-item">
                            <div class="product-item-info" data-container="product-grid" style="min-width:200px;">
                                <?php
                                $productImage = $block->getImage($product, $image);
                                ?>
                                <?php // Product Image  ?>
                                <a href="<?php echo $product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?php echo $productImage->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php echo $product->getProductUrl() ?>">
                                               <?php echo $_helper->productAttribute($product, $product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                    <?php echo $block->getProductPrice($product); ?>
                                    <div class="actions-primary">
                                        <?php if ($product->isSaleable()) { ?>
                                            <?php if ($product->getTypeInstance()->hasRequiredOptions($product)) { ?>
                                                <button class="action tocart primary"
                                                        data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($product) ?>"}}'
                                                        type="button" title="<?php echo __('Add to Cart') ?>">
                                                    <span><?php echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php } else { ?>
                                                <?php
                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getId()]);
                                                ?>
                                                <button class="action tocart primary"
                                                        data-post='<?php echo $postData; ?>'
                                                        type="button" title="<?php echo __('Add to Cart') ?>">
                                                    <span><?php echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php } ?>
                                        <?php } else { ?>
                                            <?php if ($product->getIsSalable()) { ?>
                                                <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                            <?php } else { ?>
                                                <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                        <?php
                                                    }
                                                }
                                                ?>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ol>
                    <?php
                }
            }
            ?>
        </div>
    </div>
<?php } ?>
